/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sites */
        get: operations["sites_api_sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_sites__site__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site}/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily */
        get: operations["daily_api_sites__site__daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site}/load-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Profile */
        get: operations["load_profile_api_sites__site__load_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site}/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stations */
        get: operations["stations_api_sites__site__stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions */
        get: operations["sessions_api_sites__site__sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DailyRow */
        DailyRow: {
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Is Weekend */
            is_weekend: boolean;
            /** Sessions */
            sessions: number;
            /** Identified Users */
            identified_users: number;
            /** Energy Kwh */
            energy_kwh: number;
            /** Avg Connected Hours */
            avg_connected_hours: number;
            /** Avg Idle Hours */
            avg_idle_hours: number;
            /** Share Requests Met */
            share_requests_met: number | null;
            /** Share Overstayed */
            share_overstayed: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Backend */
            backend: string;
        };
        /** LoadProfile */
        LoadProfile: {
            /** Site */
            site: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Weekdays */
            weekdays: number;
            /** Weekend Days */
            weekend_days: number;
            /** Slots */
            slots: components["schemas"]["LoadSlot"][];
        };
        /** LoadSlot */
        LoadSlot: {
            /** Slot */
            slot: number;
            /** Time */
            time: string;
            /** Weekday Avg Kw */
            weekday_avg_kw: number;
            /** Weekday Max Kw */
            weekday_max_kw: number;
            /** Weekend Avg Kw */
            weekend_avg_kw: number;
            /** Weekend Max Kw */
            weekend_max_kw: number;
        };
        /** Session */
        Session: {
            /** Session Id */
            session_id: string;
            /** Station Id */
            station_id: string;
            /** User Id */
            user_id: string | null;
            /**
             * Connected At Utc
             * Format: date-time
             */
            connected_at_utc: string;
            /**
             * Connected At Local
             * Format: date-time
             */
            connected_at_local: string;
            /**
             * Disconnected At Utc
             * Format: date-time
             */
            disconnected_at_utc: string;
            /** Connected Hours */
            connected_hours: number;
            /** Charging Hours */
            charging_hours: number;
            /** Idle Hours */
            idle_hours: number;
            /** Kwh Delivered */
            kwh_delivered: number;
            /** Kwh Requested */
            kwh_requested: number | null;
            /** Request Met */
            request_met: boolean | null;
            /** Overstayed */
            overstayed: boolean;
        };
        /** SessionPage */
        SessionPage: {
            /** Site */
            site: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Items */
            items: components["schemas"]["Session"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Site */
        Site: {
            /** Site */
            site: string;
            /** Timezone */
            timezone: string;
            /**
             * First Date
             * Format: date
             */
            first_date: string;
            /**
             * Last Date
             * Format: date
             */
            last_date: string;
            /** Sessions */
            sessions: number;
            /** Stations */
            stations: number;
            /** Energy Kwh */
            energy_kwh: number;
        };
        /** Station */
        Station: {
            /** Station Id */
            station_id: string;
            /** Space Id */
            space_id: string | null;
            /** Sessions */
            sessions: number;
            /** Total Kwh */
            total_kwh: number;
            /** Occupied Share */
            occupied_share: number;
            /** Charging Share */
            charging_share: number;
            /** Idle Share Of Occupied */
            idle_share_of_occupied: number | null;
            /**
             * First Session Date
             * Format: date
             */
            first_session_date: string;
            /**
             * Last Session Date
             * Format: date
             */
            last_session_date: string;
        };
        /** Summary */
        Summary: {
            /** Site */
            site: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Days */
            days: number;
            /** Sessions */
            sessions: number;
            /** Identified Users */
            identified_users: number;
            /** Energy Kwh */
            energy_kwh: number;
            /** Avg Connected Hours */
            avg_connected_hours: number | null;
            /** Avg Idle Hours */
            avg_idle_hours: number | null;
            /** Share Requests Met */
            share_requests_met: number | null;
            /** Share Overstayed */
            share_overstayed: number | null;
            /** Peak Kw */
            peak_kw: number | null;
            /** Peak At */
            peak_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    sites_api_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"][];
                };
            };
        };
    };
    summary_api_sites__site__summary_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                site: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_api_sites__site__daily_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                site: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_profile_api_sites__site__load_profile_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                site: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stations_api_sites__site__stations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Station"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_api_sites__site__sessions_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                station?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                site: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
